name: ee
version: 1.0.0
config-version: 2

profile: ee

restrict-access: true

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

models:
  ee:
    staging:
      +materialized: view
      +group: lakehouse
      +access: private
    marts:
      +materialized: view
      +group: lakehouse
      +access: public
