name: ee_sub_unit_1
version: 1.0.0
config-version: 2

profile: ee_sub_unit_1

restrict-access: true

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

models:
  ee_sub_unit_1:
    marts:
      +materialized: view
      +group: sub_unit_1
      +access: public
