apiVersion: v1
kind: ConfigMap
metadata:
  name: dbt-profiles
  namespace: data-platform
data:
  ee_common_profiles.yml: |
    ee_common:
      target: "{{ env_var('DBT_TARGET', 'dev') }}"
      outputs:
        dev:
          type: trino
          method: none
          user: dbt
          host: "{{ env_var('TRINO_HOST', 'localhost') }}"
          port: "{{ env_var('TRINO_PORT', '8080') | int }}"
          database: iceberg
          schema: dbt_common_dev
          threads: 4
  ee_central_profiles.yml: |
    ee_central:
      target: "{{ env_var('DBT_TARGET', 'dev') }}"
      outputs:
        dev:
          type: trino
          method: none
          user: dbt
          host: "{{ env_var('TRINO_HOST', 'localhost') }}"
          port: "{{ env_var('TRINO_PORT', '8080') | int }}"
          database: iceberg
          schema: dbt_central_dev
          threads: 4
  ee_sub_unit_1_profiles.yml: |
    ee_sub_unit_1:
      target: "{{ env_var('DBT_TARGET', 'dev') }}"
      outputs:
        dev:
          type: trino
          method: none
          user: dbt
          host: "{{ env_var('TRINO_HOST', 'localhost') }}"
          port: "{{ env_var('TRINO_PORT', '8080') | int }}"
          database: iceberg
          schema: dbt_sub_unit_1_dev
          threads: 4
