name: ee_central
version: 1.0.0
config-version: 2

profile: ee_central

restrict-access: true

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

models:
  ee_central:
    bronze:
      +materialized: table
      +group: central
      +access: private
    silver:
      +materialized: table
      +group: central
      +access: private
    gold:
      +materialized: table
      +group: central
      +access: public
