name: ee_parent
version: 1.0.0
config-version: 2

profile: ee_parent

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

models:
  ee_parent:
    reporting:
      +materialized: view
